import type { User, Job, Candidate } from '@/types';

export const seedData: { users: User[]; jobs: Job[]; candidates: Candidate[] } = {
  users: [
    {
      id: 'user-1',
      name: 'Alice Admin',
      email: 'alice@company.com',
      password: 'password',
      role: 'Admin',
      active: true,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'user-2',
      name: 'Bob Recruiter',
      email: 'bob@company.com',
      password: 'password',
      role: 'Recruiter',
      active: true,
      createdAt: '2024-01-02T00:00:00Z',
    },
    {
      id: 'user-3',
      name: 'Carol Manager',
      email: 'carol@company.com',
      password: 'password',
      role: 'Hiring Manager',
      active: true,
      createdAt: '2024-01-03T00:00:00Z',
    },
  ],
  jobs: [
    {
      id: 'job-1',
      title: 'Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      type: 'Full-time',
      description: 'Build and maintain our React-based frontend applications.',
      status: 'Open',
      createdAt: '2024-01-10T00:00:00Z',
      hiringManagerId: 'user-3',
    },
    {
      id: 'job-2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York',
      type: 'Full-time',
      description: 'Drive product strategy and roadmap.',
      status: 'Open',
      createdAt: '2024-01-12T00:00:00Z',
      hiringManagerId: 'user-3',
    },
    {
      id: 'job-3',
      title: 'Data Analyst',
      department: 'Data',
      location: 'Remote',
      type: 'Contract',
      description: 'Analyze business data and create dashboards.',
      status: 'Open',
      createdAt: '2024-01-15T00:00:00Z',
    },
    {
      id: 'job-4',
      title: 'Backend Engineer',
      department: 'Engineering',
      location: 'San Francisco',
      type: 'Full-time',
      description: 'Design and build scalable backend services.',
      status: 'Closed',
      createdAt: '2024-01-05T00:00:00Z',
    },
  ],
  candidates: [
    {
      id: 'cand-1',
      name: 'Diana Prince',
      email: 'diana@example.com',
      phone: '+1 555 100 0001',
      jobId: 'job-1',
      stage: 'Interview',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-20T10:00:00Z' },
        { stage: 'Screening', movedAt: '2024-01-22T10:00:00Z' },
        { stage: 'Interview', movedAt: '2024-01-25T10:00:00Z' },
      ],
      notes: [
        { id: 'note-1', content: 'Strong React skills, great communication.', createdAt: '2024-01-25T11:00:00Z', createdBy: 'user-2' },
      ],
      emails: [],
      documents: [],
      source: 'LinkedIn',
      createdAt: '2024-01-20T10:00:00Z',
    },
    {
      id: 'cand-2',
      name: 'Ethan Hunt',
      email: 'ethan@example.com',
      phone: '+1 555 100 0002',
      jobId: 'job-1',
      stage: 'Screening',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-21T10:00:00Z' },
        { stage: 'Screening', movedAt: '2024-01-23T10:00:00Z' },
      ],
      notes: [],
      emails: [],
      documents: [],
      source: 'Referral',
      createdAt: '2024-01-21T10:00:00Z',
    },
    {
      id: 'cand-3',
      name: 'Fiona Green',
      email: 'fiona@example.com',
      jobId: 'job-2',
      stage: 'Applied',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-22T10:00:00Z' },
      ],
      notes: [],
      emails: [],
      documents: [],
      source: 'Job Board',
      createdAt: '2024-01-22T10:00:00Z',
    },
    {
      id: 'cand-4',
      name: 'George Clark',
      email: 'george@example.com',
      jobId: 'job-2',
      stage: 'Offer',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-15T10:00:00Z' },
        { stage: 'Screening', movedAt: '2024-01-17T10:00:00Z' },
        { stage: 'Interview', movedAt: '2024-01-19T10:00:00Z' },
        { stage: 'Offer', movedAt: '2024-01-28T10:00:00Z' },
      ],
      notes: [],
      emails: [],
      documents: [],
      source: 'LinkedIn',
      createdAt: '2024-01-15T10:00:00Z',
    },
    {
      id: 'cand-5',
      name: 'Hannah Lee',
      email: 'hannah@example.com',
      jobId: 'job-3',
      stage: 'Hired',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-10T10:00:00Z' },
        { stage: 'Screening', movedAt: '2024-01-12T10:00:00Z' },
        { stage: 'Interview', movedAt: '2024-01-14T10:00:00Z' },
        { stage: 'Offer', movedAt: '2024-01-18T10:00:00Z' },
        { stage: 'Hired', movedAt: '2024-01-22T10:00:00Z' },
      ],
      notes: [],
      emails: [],
      documents: [],
      source: 'Referral',
      createdAt: '2024-01-10T10:00:00Z',
    },
    {
      id: 'cand-6',
      name: 'Ivan Drago',
      email: 'ivan@example.com',
      jobId: 'job-1',
      stage: 'Rejected',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-01-18T10:00:00Z' },
        { stage: 'Screening', movedAt: '2024-01-20T10:00:00Z' },
        { stage: 'Rejected', movedAt: '2024-01-21T10:00:00Z' },
      ],
      notes: [
        { id: 'note-2', content: 'Not enough experience with TypeScript.', createdAt: '2024-01-21T09:00:00Z', createdBy: 'user-2' },
      ],
      emails: [],
      documents: [],
      source: 'Job Board',
      createdAt: '2024-01-18T10:00:00Z',
    },
  ],
};
