import type { User, Job, Candidate, CustomFieldDef } from '@/types';
import { generateId } from '@/lib/id';

export function seedData() {
  const users: User[] = [
    {
      id: 'u1',
      name: 'Alice Admin',
      email: 'admin@example.com',
      role: 'Admin',
      active: true,
      createdAt: '2024-01-01T00:00:00Z',
      passwordHash: 'password',
    },
    {
      id: 'u2',
      name: 'Bob Recruiter',
      email: 'recruiter@example.com',
      role: 'Recruiter',
      active: true,
      createdAt: '2024-01-02T00:00:00Z',
      passwordHash: 'password',
    },
    {
      id: 'u3',
      name: 'Carol Manager',
      email: 'manager@example.com',
      role: 'Hiring Manager',
      active: true,
      createdAt: '2024-01-03T00:00:00Z',
      passwordHash: 'password',
    },
  ];

  const jobs: Job[] = [
    {
      id: 'j1',
      title: 'Senior Frontend Engineer',
      department: 'Engineering',
      location: 'Remote',
      status: 'Open',
      description: 'Build and maintain our React-based frontend applications.',
      requirements: '5+ years React experience, TypeScript, CSS-in-JS',
      employmentType: 'Full-time',
      pipelineType: 'Technical',
      createdAt: '2024-01-10T00:00:00Z',
    },
    {
      id: 'j2',
      title: 'Product Manager',
      department: 'Product',
      location: 'New York, NY',
      status: 'Open',
      description: 'Lead product strategy and roadmap for our core platform.',
      requirements: '3+ years PM experience, strong analytical skills',
      employmentType: 'Full-time',
      pipelineType: 'Standard',
      createdAt: '2024-01-12T00:00:00Z',
    },
    {
      id: 'j3',
      title: 'UX Designer',
      department: 'Design',
      location: 'San Francisco, CA',
      status: 'Open',
      description: 'Design intuitive user experiences across our product suite.',
      requirements: 'Portfolio required, Figma proficiency, 3+ years experience',
      employmentType: 'Full-time',
      pipelineType: 'Standard',
      createdAt: '2024-01-15T00:00:00Z',
    },
    {
      id: 'j4',
      title: 'Data Analyst',
      department: 'Analytics',
      location: 'Chicago, IL',
      status: 'Draft',
      description: 'Analyze data to support business decisions.',
      requirements: 'SQL, Python, data visualization tools',
      employmentType: 'Full-time',
      pipelineType: 'Standard',
      createdAt: '2024-01-20T00:00:00Z',
    },
  ];

  const candidates: Candidate[] = [
    {
      id: generateId(),
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone: '+1 555 100 0001',
      jobId: 'j1',
      jobTitle: 'Senior Frontend Engineer',
      stage: 'Interview',
      rating: 4,
      tags: ['React', 'TypeScript'],
      customFields: {},
      linkedinUrl: 'https://linkedin.com/in/janesmith',
      source: 'LinkedIn',
      createdAt: '2024-02-01T00:00:00Z',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-02-01T00:00:00Z', movedBy: 'system' },
        { stage: 'Screening', movedAt: '2024-02-03T00:00:00Z', movedBy: 'u2' },
        { stage: 'Interview', movedAt: '2024-02-07T00:00:00Z', movedBy: 'u2' },
      ],
      notes: [
        { id: generateId(), content: 'Strong React skills, good culture fit.', createdAt: '2024-02-05T00:00:00Z', createdBy: 'Bob Recruiter' },
      ],
      emails: [],
      documents: [],
    },
    {
      id: generateId(),
      name: 'John Doe',
      email: 'john.doe@example.com',
      phone: '+1 555 100 0002',
      jobId: 'j1',
      jobTitle: 'Senior Frontend Engineer',
      stage: 'Screening',
      rating: 3,
      tags: ['Vue', 'JavaScript'],
      customFields: {},
      linkedinUrl: '',
      source: 'Indeed',
      createdAt: '2024-02-05T00:00:00Z',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-02-05T00:00:00Z', movedBy: 'system' },
        { stage: 'Screening', movedAt: '2024-02-08T00:00:00Z', movedBy: 'u2' },
      ],
      notes: [],
      emails: [],
      documents: [],
    },
    {
      id: generateId(),
      name: 'Emily Chen',
      email: 'emily.chen@example.com',
      phone: '+1 555 100 0003',
      jobId: 'j2',
      jobTitle: 'Product Manager',
      stage: 'Offer',
      rating: 5,
      tags: ['Strategy', 'Analytics'],
      customFields: {},
      linkedinUrl: 'https://linkedin.com/in/emilychen',
      source: 'Referral',
      createdAt: '2024-02-08T00:00:00Z',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-02-08T00:00:00Z', movedBy: 'system' },
        { stage: 'Screening', movedAt: '2024-02-10T00:00:00Z', movedBy: 'u2' },
        { stage: 'Interview', movedAt: '2024-02-14T00:00:00Z', movedBy: 'u2' },
        { stage: 'Offer', movedAt: '2024-02-20T00:00:00Z', movedBy: 'u1' },
      ],
      notes: [],
      emails: [],
      documents: [],
    },
    {
      id: generateId(),
      name: 'Michael Brown',
      email: 'michael.brown@example.com',
      phone: '+1 555 100 0004',
      jobId: 'j3',
      jobTitle: 'UX Designer',
      stage: 'Applied',
      rating: 0,
      tags: ['Figma', 'UX'],
      customFields: {},
      linkedinUrl: '',
      source: 'Public Apply',
      createdAt: '2024-02-12T00:00:00Z',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-02-12T00:00:00Z', movedBy: 'system' },
      ],
      notes: [],
      emails: [],
      documents: [],
    },
    {
      id: generateId(),
      name: 'Sarah Wilson',
      email: 'sarah.wilson@example.com',
      phone: '+1 555 100 0005',
      jobId: 'j2',
      jobTitle: 'Product Manager',
      stage: 'Rejected',
      rating: 2,
      tags: [],
      customFields: {},
      linkedinUrl: '',
      source: 'LinkedIn',
      createdAt: '2024-02-09T00:00:00Z',
      stageHistory: [
        { stage: 'Applied', movedAt: '2024-02-09T00:00:00Z', movedBy: 'system' },
        { stage: 'Screening', movedAt: '2024-02-11T00:00:00Z', movedBy: 'u2' },
        { stage: 'Rejected', movedAt: '2024-02-13T00:00:00Z', movedBy: 'u1' },
      ],
      notes: [],
      emails: [],
      documents: [],
    },
  ];

  const customFields: CustomFieldDef[] = [
    { id: 'cf1', label: 'Expected Salary', type: 'text' },
    { id: 'cf2', label: 'Availability', type: 'date' },
  ];

  return { users, jobs, candidates, customFields };
}
